/* WebGAL director authoring module: deliberately DOM-safe and selector driven. */
(function(root){'use strict';
 const esc=s=>String(s==null?'':s), q=(d,t,l)=>{const e=d.createElement(t);if(l)e.textContent=l;return e};
 function install(){if(typeof project==='undefined'||!project||document.getElementById('directorEditorBtn'))return;const b=q(document,'button','🎬 WebGAL 演出');b.id='directorEditorBtn';b.title='打开六类演出编辑器';(document.querySelector('.header-primary')||document.querySelector('header')||document.body).appendChild(b);b.onclick=show;}
 function show(){const d=document, p=project, sc=typeof selectedScene==='function'&&selectedScene()||p.scenes&&p.scenes[0];const old=d.getElementById('directorEditorModal');if(old)old.remove();const m=q(d,'div');m.id='directorEditorModal';m.setAttribute('role','dialog');Object.assign(m.style,{position:'fixed',inset:'5%',zIndex:9999,background:'#fff',color:'#222',padding:'20px',overflow:'auto',border:'2px solid #fb7299',borderRadius:'14px'});const title=q(d,'h2','WebGAL 演出导演');m.append(title,q(d,'p','选择功能并编辑当前项目。所有输入均按字面保存；条件由运行时安全解析器执行。'));const tabs=q(d,'div');const body=q(d,'div');m.append(tabs,body);const add=(label,fn)=>{const x=q(d,'button',label);x.onclick=()=>{body.replaceChildren();fn(body)};tabs.append(x)};
 function mutate(fn){if(typeof commitUndoSnapshot==='function')commitUndoSnapshot();fn();if(typeof saveEditor==='function')saveEditor();if(typeof renderAll==='function')renderAll();}
 function input(parent,label,value,cb,type='text'){const w=q(d,'label');w.append(q(d,'span',label+' '));const x=q(d,'input');x.type=type==='text'?'text':type;x.value=esc(value);if(type==='checkbox')x.checked=value===true;x.onchange=()=>mutate(()=>cb(type==='checkbox'?String(x.checked):x.value));w.append(x);parent.append(w,q(d,'br'));return x}
 function scenes(parent){const s=sc||{};parent.append(q(d,'h3','场景继承、主题与公共剧情'));['background','characters','bgm'].forEach(k=>input(parent,'继承'+k,s.inheritStage&&s.inheritStage[k],v=>{s.inheritStage=s.inheritStage||{};s.inheritStage[k]=v==='true'},'checkbox'));input(parent,'主题 ID',s.themeId||'',v=>s.themeId=v);['mode','target','returnTo','result','value'].forEach(k=>input(parent,k,(s.flow||{})[k]||'',v=>{s.flow=s.flow||{};s.flow[k]=v}));input(parent,'args JSON',JSON.stringify((s.flow||{}).args||{}),v=>{try{s.flow=s.flow||{};s.flow.args=JSON.parse(v)}catch(e){}});parent.append(q(d,'p','返回值支持 {变量}；call 需要 target 与 returnTo。重置复选框表示该资源从当前场景重新取值。'))}
 function choices(parent){const cs=sc&&sc.choices||[];cs.forEach((c,i)=>{parent.append(q(d,'h4','选项 '+(i+1)+'：'+esc(c.text)));input(parent,'可见条件',c.cond||'',v=>c.cond=v);input(parent,'启用条件',c.enableCond||'',v=>c.enableCond=v);input(parent,'禁用原因',c.disabledReason||'',v=>c.disabledReason=v)});if(!cs.length)parent.append(q(d,'p','当前场景没有选项。'))}
 function chars(parent){(p.characters||[]).forEach(c=>{parent.append(q(d,'h4',esc(c.name||c.id)));['mouthOpen','mouthHalf','mouthClosed','eyesClosed'].forEach(k=>input(parent,k,c.portrait&&c.portrait[k]||'',v=>{c.portrait=c.portrait||{};c.portrait[k]=v}));input(parent,'blinkInterval',c.portrait&&c.portrait.blinkInterval||4000,v=>{c.portrait=c.portrait||{};c.portrait.blinkInterval=Number(v)||4000},'number')})}
 function cues(parent){const ds=sc&&sc.dialogues||[];const sel=q(d,'select');ds.forEach((x,i)=>{const o=q(d,'option','对白 '+(i+1)+' '+esc(x.text).slice(0,30));o.value=i;sel.append(o)});if(!ds.length)parent.append(q(d,'p','当前场景没有对白，请先添加一条对白。'));else{parent.append(sel);const render=()=>{parent.querySelectorAll('.cue').forEach(e=>e.remove());const x=ds[Number(sel.value)];if(!x)return;(x.cues||[]).forEach((c,i)=>{const w=q(d,'div');w.className='cue';w.append(q(d,'b','Cue '+(i+1)+' '));['at','type','target','expressionId','themeId','x','y','duration','keep'].forEach(k=>input(w,k,c[k]||'',v=>c[k]=k==='at'||k==='duration'||k==='x'||k==='y'?Number(v):k==='keep'?v==='true':v));const rm=q(d,'button','删除');rm.onclick=()=>mutate(()=>{x.cues.splice(i,1);render()});w.append(rm);parent.append(w)});const addb=q(d,'button','新增 cue');addb.onclick=()=>mutate(()=>{x.cues=x.cues||[];x.cues.push({at:0,type:'expression',target:'',duration:1000,keep:true});render()});parent.append(addb)};sel.onchange=render;render();}}
 function templates(parent){p.director=p.director||{version:1,templates:[]};const name=input(parent,'模板名称','新模板',v=>{});const cap=q(d,'button','捕获当前 UI+首页');cap.onclick=()=>mutate(()=>p.director.templates.push({id:'tpl-'+Date.now(),name:name.value,version:1,ui:JSON.parse(JSON.stringify(p.ui||{})),home:JSON.parse(JSON.stringify(p.home||{}))}));parent.append(cap);p.director.templates.forEach(t=>{const row=q(d,'div',esc(t.name)+' v'+t.version);const ap=q(d,'button','应用');ap.onclick=()=>mutate(()=>{p.ui=JSON.parse(JSON.stringify(t.ui||{}));p.home=JSON.parse(JSON.stringify(t.home||{}))});const rm=q(d,'button','删除');rm.onclick=()=>mutate(()=>p.director.templates=p.director.templates.filter(x=>x.id!==t.id));row.append(ap,rm);parent.append(row)})}
 add('场景',scenes);add('选项',choices);add('角色库',chars);add('对白 cues',cues);add('模板',templates);const help=q(d,'details');help.append(q(d,'summary','详细帮助'),q(d,'p','继承控制舞台资源；可见与启用条件分离；cue 在 UTF-16 字符阈值触发；portrait 四图由运行时安全回退；模板保存版本化 UI 与首页。预览始终从真正入口开始。'));m.append(help);const close=q(d,'button','关闭');close.onclick=()=>m.remove();m.append(close);d.body.append(m);m.addEventListener('click',e=>{if(e.target===m)m.remove()});d.addEventListener('keydown',function z(e){if(e.key==='Escape'){m.remove();d.removeEventListener('keydown',z)}});}
 if(typeof document!=='undefined'&&(document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install):install()),root)root.DirectorEditor={install};
})(typeof globalThis!=='undefined'?globalThis:this);
