/* Director authoring: live project resolution and atomic undoable edits. */
(function(root){'use strict';
const copy=v=>JSON.parse(JSON.stringify(v)), el=(tag,text)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;return e;};
function install(){if(typeof project==='undefined'||!project||document.getElementById('directorEditorBtn'))return;const b=el('button','🎬 WebGAL 演出');b.id='directorEditorBtn';(document.querySelector('.header-primary')||document.body).append(b);b.onclick=show;}
function show(){document.getElementById('directorEditorModal')?.remove();const m=el('div');m.id='directorEditorModal';m.setAttribute('role','dialog');m.setAttribute('aria-label','WebGAL 演出导演');Object.assign(m.style,{position:'fixed',inset:'5%',zIndex:9999,background:'#20212d',color:'#eee',padding:'20px',overflow:'auto',border:'2px solid #fb7299',borderRadius:'14px'});let tab='场景',lineIndex=0;const body=el('div'),status=el('p'),tabs=el('div');status.setAttribute('role','status');m.append(el('h2','WebGAL 演出导演'),tabs,status,body);document.body.append(m);
const scene=()=>typeof selectedScene==='function'?selectedScene():project.scenes?.[0];
const tell=(s,bad=false)=>{status.textContent=s;status.style.color=bad?'#ff9696':'#9fe3bb';};
function mutate(fn){try{commitUndoSnapshot();fn();commitUndoSnapshot();saveEditor();renderAll();tell('已保存，可撤销');render();}catch(e){tell(e.message,true);}}
function button(parent,label,fn){const b=el('button',label);b.type='button';b.onclick=fn;parent.append(b);return b;}
function field(parent,label,value,change,type='text',options){const w=el('label'),name=el('span',label+' ');w.style.display='block';w.style.margin='10px 0';let x;if(options){x=el('select');for(const [v,n] of options){const o=el('option',n);o.value=v;x.append(o);}if(value&&!options.some(o=>o[0]===value)){const o=el('option','未找到：'+value);o.value=value;x.append(o);}}else{x=el('input');x.type=type;}x.setAttribute('aria-label',label);if(type==='checkbox')x.checked=value===true;else x.value=value??'';x.onchange=()=>{try{let v=type==='checkbox'?x.checked:type==='number'?Number(x.value):x.value;if(type==='number'&&!Number.isFinite(v))throw Error(label+' 必须是有效数字');change(v);}catch(e){tell(e.message,true);}};w.append(name,x);parent.append(w);return x;}
const templates=()=>project.director?.templates||[];
const scenes=()=>[['','未设置'],...(project.scenes||[]).map(s=>[s.id,s.name||s.id])];
const themes=()=>[['','默认主题'],...templates().map(t=>[t.id,t.name||t.id])];
function render(){body.replaceChildren();const s=scene();if(tab==='场景'){if(!s){body.append(el('p','没有选中的场景'));return;}body.append(el('h3',s.name||s.id));for(const [k,n] of [['background','背景'],['characters','角色'],['bgm','BGM']])field(body,'继承'+n,s.inheritStage?.[k],v=>mutate(()=>{const a=scene();a.inheritStage={...a.inheritStage,[k]:v};}),'checkbox');field(body,'主题',s.themeId,v=>mutate(()=>scene().themeId=v),'text',themes());field(body,'流程',s.flow?.mode||'next',v=>mutate(()=>{scene().flow={...scene().flow,mode:v};}),'text',[['next','正常推进'],['call','调用公共剧情'],['return','返回调用处']]);for(const [k,n] of [['target','调用目标'],['returnTo','返回场景']])field(body,n,s.flow?.[k],v=>mutate(()=>scene().flow={...scene().flow,[k]:v}),'text',scenes());for(const [k,n] of [['result','返回结果变量'],['value','返回值']])field(body,n,s.flow?.[k],v=>mutate(()=>scene().flow={...scene().flow,[k]:v}));field(body,'参数 JSON',JSON.stringify(s.flow?.args||{}),v=>{const args=JSON.parse(v);if(!args||typeof args!=='object'||Array.isArray(args))throw Error('参数必须为 JSON 对象');mutate(()=>scene().flow={...scene().flow,args});});}
if(tab==='选项'){if(!s?.choices?.length)body.append(el('p','当前场景没有选项'));(s?.choices||[]).forEach((c,i)=>{const group=el('fieldset');group.append(el('legend',c.text||'选项'));for(const [k,n] of [['cond','可见条件'],['enableCond','启用条件'],['disabledReason','禁用原因']])field(group,n,c[k],v=>{if(k!=='disabledReason'&&v&&typeof validateCond==='function'&&!validateCond(v))throw Error('条件表达式无效');mutate(()=>scene().choices[i][k]=v);});body.append(group);});}
if(tab==='角色库'){if(!project.characters?.length)body.append(el('p','请先在角色库添加角色'));(project.characters||[]).forEach(c=>{const group=el('fieldset');group.append(el('legend',c.name||c.id));const live=()=>project.characters.find(x=>x.id===c.id);for(const k of ['mouthOpen','mouthHalf','mouthClosed','eyesClosed']){field(group,k,c.portrait?.[k],v=>mutate(()=>live().portrait={...live().portrait,[k]:v}));const upload=field(group,'上传 '+k,'',()=>{},'file');upload.accept='image/*';upload.onchange=async()=>{try{const file=upload.files[0];if(!file)return;if(!file.type.startsWith('image/'))throw Error('请选择图片');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('图片读取失败'));r.readAsDataURL(file);});mutate(()=>live().portrait={...live().portrait,[k]:data});}catch(e){tell(e.message,true);}};}field(group,'眨眼间隔 ms',c.portrait?.blinkInterval??4000,v=>{if(v<1000)throw Error('眨眼间隔至少 1000 ms');mutate(()=>live().portrait={...live().portrait,blinkInterval:v});},'number');body.append(group);});body.append(el('p','嘴型按打字/语音播放状态模拟，不分析音频振幅；闭眼图优先。请上传尺寸一致的完整立绘。'));}
if(tab==='对白 cues'){const ds=s?.dialogues||[];if(!ds.length){body.append(el('p','当前场景没有对白，请先添加一条对白。'));return;}lineIndex=Math.min(lineIndex,ds.length-1);field(body,'对白',String(lineIndex),v=>{lineIndex=Number(v);render();},'text',ds.map((d,i)=>[String(i),'对白 '+(i+1)+' '+(d.text||'').slice(0,30)]));const current=()=>scene().dialogues[lineIndex];(ds[lineIndex].cues||[]).forEach((c,i)=>{const w=el('fieldset');w.className='cue';w.append(el('legend','Cue '+(i+1)));const set=(k,v)=>mutate(()=>current().cues[i][k]=v);field(w,'触发字符数',c.at??0,v=>{if(v<0)throw Error('字符数不能为负');set('at',v);},'number');field(w,'类型',c.type||'expression',v=>set('type',v),'text',[['expression','表情'],['move','移动'],['theme','主题']]);field(w,'目标角色',c.target,v=>set('target',v),'text',[['','未设置'],...(s.characters||[]).map(ch=>[ch.id,ch.name||ch.id])]);const ch=s.characters?.find(ch=>ch.id===c.target),lib=project.characters?.find(x=>x.id===ch?.charId);field(w,'表情',c.expressionId,v=>set('expressionId',v),'text',[['','默认表情'],...(lib?.expressions||[]).map(e=>[e.id,e.name||e.id])]);field(w,'Cue 主题',c.themeId,v=>set('themeId',v),'text',themes());for(const [k,n,def] of [['x','X 百分比',50],['y','Y 百分比',88],['duration','持续毫秒',1000]])field(w,n,c[k]??def,v=>{if(k==='duration'&&v<0)throw Error('持续毫秒不能为负');set(k,v);},'number');field(w,'跨对白保持移动',c.keep===true,v=>set('keep',v),'checkbox');button(w,'删除 cue',()=>mutate(()=>current().cues.splice(i,1)));body.append(w);});button(body,'新增 cue',()=>mutate(()=>{const d=current();d.cues=d.cues||[];d.cues.push({at:0,type:'expression',target:s.characters?.[0]?.id||'',x:50,y:88,duration:1000,keep:true});}));}
if(tab==='模板'){const name=field(body,'模板名称','新模板',()=>{});button(body,'捕获当前 UI+首页',()=>mutate(()=>{project.director={version:1,templates:[...templates(),{id:'tpl-'+Date.now(),name:name.value||'新模板',version:1,ui:copy(project.ui||{}),home:copy(project.home||{})}]};}));for(const t of templates()){const row=el('div',t.name+' v'+t.version);button(row,'应用 '+t.name,()=>mutate(()=>{const base=typeof defaultUILayout==='function'?defaultUILayout():{};for(const [k,v] of Object.entries(t.ui||{}))base[k]={...base[k],...copy(v)};project.ui=base;project.home={...project.home,...copy(t.home||{})};}));button(row,'删除 '+t.name,()=>mutate(()=>project.director.templates=templates().filter(x=>x.id!==t.id)));body.append(row);}button(body,'导出模板 JSON',()=>{const blob=new Blob([JSON.stringify({version:1,templates:templates()},null,2)],{type:'application/json'}),a=el('a');a.href=URL.createObjectURL(blob);a.download='director-templates.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);tell('已导出模板');});const f=field(body,'导入模板 JSON','',()=>{},'file');f.accept='.json,application/json';f.onchange=async()=>{try{const file=f.files[0];if(!file)return;const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.templates))throw Error('模板文件版本无效，要求 version:1');const seen=new Set();for(const t of data.templates){if(t.version!==1||typeof t.id!=='string'||!t.id||seen.has(t.id)||!t.ui||typeof t.ui!=='object'||Array.isArray(t.ui))throw Error('模板结构或 ID 无效');seen.add(t.id);}mutate(()=>{const map=new Map(templates().map(t=>[t.id,t]));for(const t of data.templates)map.set(t.id,copy(t));project.director={version:1,templates:[...map.values()]};});}catch(e){tell(e.message,true);}};}}
for(const name of ['场景','选项','角色库','对白 cues','模板'])button(tabs,name,()=>{tab=name;render();});
button(tabs,'撤销',()=>{undoEditor();render();});button(tabs,'重做',()=>{redoEditor();render();});
function close(){m.remove();document.removeEventListener('keydown',key);}
button(tabs,'从入口预览',()=>{if(!project.scenes?.some(s=>s.id===project.startScene)){tell('项目入口场景无效',true);return;}close();openPlayer(project);startNewGame();});button(tabs,'关闭',close);
const help=el('details');help.append(el('summary','使用步骤'),el('p','先选择场景，设置继承资源；在对白 cues 中新增事件，填写触发字符数和目标。移动坐标为舞台百分比，0 是有效值。模板捕获当前 UI 与首页，可导出 JSON 后导入其他项目。call 需要目标与返回场景，参数为 JSON 对象；返回值支持 {变量}。使用“从入口预览”检查前序场景继承。所有修改自动保存，可撤销/重做。'));m.append(help);
function key(e){if(e.key==='Escape'){e.preventDefault();close();}}document.addEventListener('keydown',key);render();}
root.DirectorEditor={install,show};if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();}
})(globalThis);
