'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),vm=require('vm');
const {ExprParser}=require('./condition_parser');
function scanProject(project,root=__dirname){
 const r={ok:true,files:[],errors:[],warnings:[],resources:[],platforms:{},credentials:{windows:'Unsigned; certificate required only for trusted signed distribution',macos:'Developer ID and Apple notarization account required for trusted distribution',linux:'No mandatory code-signing certificate; repository/store credentials depend on distribution channel'}};
 for(const name of ['index.html','server.js','debug_workbench.js','workbench_ui.js','condition_parser.js']){const f=path.join(root,name);if(!fs.existsSync(f)){r.errors.push('Missing '+name);continue;}const data=fs.readFileSync(f);r.files.push({file:name,bytes:data.length,sha256:crypto.createHash('sha256').update(data).digest('hex')});try{if(name.endsWith('.js'))new vm.Script(data.toString());else{for(const m of data.toString().matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(m[1].trim())new vm.Script(m[1]);}}catch(e){r.errors.push(name+': '+e.message);}}
 const exe=path.join(root,'native-player/dist/visual-novel-native.exe');let validPE=false;if(fs.existsSync(exe)){const b=fs.readFileSync(exe);const offset=b.length>64?b.readUInt32LE(60):0;validPE=b.subarray(0,2).toString()==='MZ'&&offset>0&&offset+4<=b.length&&b.subarray(offset,offset+4).equals(Buffer.from([80,69,0,0]));}
 r.platforms={web:{ready:r.errors.length===0,command:'npm run build:web'},windows:{ready:validPE,command:'npm run build:windows',runtime:'WinForms/GDI+',verification:'PE structure only; native integration test required'},macos:{ready:false,command:'npm run build:macos',blocker:'No macOS native player implementation or macOS build host. Web package works in a browser.'},linux:{ready:false,command:'npm run build:linux',blocker:'No Linux native player implementation. WinForms/GDI+ cannot be relabeled as Linux. Web package works in a browser.'}};
 if(project){const scenes=project.scenes||[],ids=new Set(scenes.map(s=>s.id));if(!ids.has(project.startScene))r.errors.push('Invalid start scene');if(ids.size!==scenes.length)r.errors.push('Duplicate scene IDs');for(const s of scenes){for(const target of [s.next,...(s.choices||[]).map(c=>c.target),...(s.autoBranches||[]).map(c=>c.target)].filter(Boolean))if(!ids.has(target))r.errors.push(s.id+': missing target '+target);for(const b of [...s.choices||[],...s.autoBranches||[]])if(b.cond)try{const p=new ExprParser(b.cond,Object.fromEntries(['chance','hourNow','minuteNow','hourBetween','sceneRead','sceneCount','endings','endingSeen','abs'].map(n=>[n,()=>0])));p.parse();}catch(e){r.errors.push(s.id+': '+e.message);}}
 const walk=(v,key='project')=>{if(typeof v==='string'&&/^(https?:|data:|blob:|file:)/i.test(v)){r.resources.push({path:key,kind:v.split(':')[0],bytes:Buffer.byteLength(v)});if(/^https?:/.test(v))r.warnings.push(key+': external resource requires network; availability unverified');if(/^(blob:|file:)/.test(v))r.errors.push(key+': nonportable resource');if(/^data:image\/svg/.test(v))r.warnings.push(key+': Windows export must rasterize SVG');}else if(v&&typeof v==='object')for(const [k,c]of Object.entries(v))walk(c,key+'.'+k);};walk(project);
 }
 r.ok=r.errors.length===0;return r;
}
if(require.main===module){const r=scanProject(process.argv[2]?JSON.parse(fs.readFileSync(process.argv[2],'utf8')):undefined);console.log(JSON.stringify(r,null,2));process.exitCode=r.ok?0:1;}
module.exports={scanProject};
